<?php

namespace App\Repository;

/**
 * NotificationContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationContentRepository extends \Doctrine\ORM\EntityRepository
{
}
