<?php
namespace App\Repository;

/**
 * HeaderFooterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderFooterRepository extends \Doctrine\ORM\EntityRepository
{
}
