<?php
namespace App\Repository;

/**
 * NeobeAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NeobeAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
