<?php

namespace App\Repository;

/**
 * NotificationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
