swiftmailer:
    stream_options:
            ssl:
                verify_peer: false
                verify_peer_name: false

    transport: "%mailer_transport%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
