resources:
  App\Entity\User:
    collectionOperations : {}
    itemOperations:
      get_token:
        route_name: 'get_token'
        controller: 'App\Controller\AuthenticationController'
        swagger_context:
          summary: Get token authentication to call all api's
          parameters:
            -
              name : body
              in: body
              schema:
                type : object
                properties:
                  username:
                    type: string
                    required: true
                    description: Login email
                  password:
                    type: string
                    required: true
                    description: Password
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  data:
                    type : object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      data:
                        type: string
                        description: contain the token
            401:
              description: Password not valid
            404:
              description: User not found

      create_account:
        route_name: 'api_create_account'
        controller: 'App\Controller\NeobeSafeDataController'
        swagger_context:
          summary: Create account to neobe safedata
          parameters:
            -
              name : body
              in: body
              schema:
                type : object
                properties:
                  company_name:
                    type: string
                    description: Company name
                  zip_code:
                    type: string
                    description: zip code
                  country:
                    type: string
                    description: country
                  city:
                    type: string
                    description: City
                  civility:
                    type: integer
                    description: civility
                  firstname:
                    type: string
                    description: firstname
                  lastname:
                    type: string
                    description: lastname
                  phone:
                    type: string
                    description:  phone number
#                  mobile:
#                    type: string
#                   description:  mobile phone number
                  email:
                    type: string
                    description: email
                  nb_licence:
                    type: string
                    description: Nb licence
                  volume_size:
                    type: string
                    description: Total volume size
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  data:
                    type : object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      data:
                        type: string
                        description: contain the token
            500:
              description: Internal server error