resources:
  App\Entity\User:
    collectionOperations : {}
    itemOperations:
      get_token:
        route_name: 'get_token'
        controller: 'App\Controller\Login'
        swagger_context:
          summary: Get token authentication to call all api's
          parameters:
            -
              name : body
              in: body
              schema:
                type : object
                properties:
                  username:
                    type: string
                    required: true
                    description: Login email
                  password:
                    type: string
                    required: true
                    description: Password
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  data:
                    type : object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      data:
                        type: string
                        description: contain the token
            401:
              description: Password not valid
            404:
              description: User not found

