resources:
  App\Entity\Api\Partner:
    collectionOperations: {}
    itemOperations:
      get_token:
        route_name: 'get_token'
        controller: 'App\Controller\AuthenticationController'
        swagger_context:
          summary: Get token authentication to call all api's
          parameters:
            -
              name : body
              in: body
              schema:
                type : object
                properties:
                  username:
                    type: string
                    required: true
                    description: Login email
                  password:
                    type: string
                    required: true
                    description: Password
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  data:
                    type : object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      data:
                        type: string
                        description: contain the token
            401:
              description: Password not valid
            404:
              description: User not found

      create_account:
        route_name: 'api_create_account'
        controller: 'App\Controller\NeobeSafeDataController'
        swagger_context:
          summary: Create account to Neobe
          parameters:
            -
              name : body
              in: body
              schema:
                type : object
                properties:
                  society:
                    type: string
                    description: Nom du société
                    required: true
                  address_1:
                    type: string
                    description: Adresse 1
                  address_2:
                    type: string
                    description: Adresse 2
                  zip_code:
                    type: string
                    description: Code postal
                  city:
                    type: string
                    description: Ville
                  country:
                    type: string
                    description: Pays
                  civility:
                    type: string
                    description: Civilité [M|MLLE|MME]
                  lastname:
                    type: string
                    description: Nom
                    required: true
                  firstname:
                    type: string
                    description: Prénom
                    required: true
                  phone:
                    type: integer
                    description:  Numéro de téléphone
                  mobile:
                    type: integer
                    description:  Numéro du mobile
                  email:
                    type: string
                    description: email
                    required: true
                  category:
                    type: integer
                    description: Categorie [1|2]
                    required: true
                  nb_licence:
                    type: integer
                    required: true
                    description: Nombre de licence [2|5|10]
                  volume_size:
                    type: integer
                    required: true
                    description: Volume total de sauvegarde [40|100|1200]
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  data:
                    type : object
                    properties:
                      code:
                        type: integer
                      message:
                        type: string
                      data:
                        type: string
                        description: contain the token
            500:
              description: Internal server error

      partner_clients:
        route_name: 'api_partner_clients'
        controller: 'App\Controller\NeobeSafeDataController'
        swagger_context:
          summary: List of clients created by a partner
          parameters:
            -
              name : id
              in: path
              type: integer
              required: true
              description: Id neobe of the partner
          responses:
            200:
              description: Success
              schema:
                type: object
                properties:
                  partner_id:
                    type: integer
                    description: Partner neobe id
                  partner_name:
                    type: string
                    description: Partner society name
                  clients:
                    type : array
                    items :
                      type: object
                      properties:
                        id_client:
                          type: integer
                          description: Client neobe Id
                        society:
                          type: string
                          description: Society name
                        lastname:
                          type: string
                          description: Lastname
                        firstname:
                          type: string
                          description: Firstname
                        civility:
                          type: string
                          description: Civility
                        nb_licences:
                          type: integer
                          description: Nb licences
                        volume_size_Go:
                          type: integer
                          description: volume size
                        date_inscription:
                          type: string
                          description: Inscription date
            400:
              description: Mandatory parameter id invalid
            404:
              description: Partner not found
            500:
              description: Internal server error