# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.mail_automatique_manager:
        class: App\Manager\EmailAutomatiqueManager
        arguments: ['@doctrine.orm.entity_manager','App\Entity\EmailAutomatique']
        public: true
    
    app.client_manager:
        class: App\Manager\ClientManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\Client']
        public: true
    app.folder_manager:
        class: App\Manager\FolderManager
        arguments: [
          '@doctrine.orm.entity_manager','App\Entity\Folder',
          '@event_dispatcher',
          '@security.token_storage',
          '@app.file_manager',
          '@translator',
          '@app.folder_user_manager'
          ]
        public: true

    app.file_manager:
        class: App\Manager\FileManager
        arguments: ['@doctrine.orm.entity_manager','App\Entity\File','@event_dispatcher','@security.token_storage','@app.openstack.objectstore', '@translator']
        public: true
    app.invitation_request_manager:
        class: App\Manager\InvitationRequestManager
        arguments: [
          '@event_dispatcher',
          '@doctrine.orm.entity_manager',
          'App\Entity\InvitationRequest',
          '@app.file_manager',
          '@app.folder_manager',
          '@app.mailer',
          '@app.utils',
          '@security.token_storage',
          '@app.folder_user_manager',
          '@app.file_user_manager'
          ]
        public: true
    app.folder_user_manager:
        class: App\Manager\FolderUserManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\FolderUser']
        public: true
    app.file_user_manager:
        class: App\Manager\FileUserManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\FileUser']
        public: true
    app.news_manager:
        class: App\Manager\NewsManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\News', '@translator']
        public: true
    app.comment_manager:
            class: App\Manager\CommentManager
            arguments: [
              '@doctrine.orm.entity_manager',
              'App\Entity\Comment',
              '@event_dispatcher',
              '@app.utils',
              '@security.token_storage'
              ]
            public: true

    app.mailer:
        class: App\Services\Mailer
        arguments: ['@service_container','@mailer']
        public: true

    app.folder_log_manager:
        class: App\Manager\FolderLogManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\FolderLog']
        public: true

    app.file_log_manager:
        class: App\Manager\FileLogManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\FileLog']
        public: true

    app.user_manager:
        class: App\Manager\UserManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\User']
        public: true

    app.event.folder:
        class: App\EventListener\FolderListener
        arguments: ['@app.folder_log_manager', '@doctrine.orm.entity_manager', '@security.token_storage', '@translator']
        tags:
            - { name: kernel.event_listener, event: folder.on.lock, method: onLockedFolder}
            - { name: kernel.event_listener, event: folder.on.unlock, method: onUnlockedFolder}
            - { name: kernel.event_listener, event: folder.on.creation, method: onCreateFolder}
            - { name: kernel.event_listener, event: folder.on.rename, method: onRenameFolder}
            - { name: kernel.event_listener, event: folder.on.delete, method: onDeleteFolder}
            - { name: kernel.event_listener, event: folder.on.change_owner, method: onChangeFolderOwner}
            - { name: kernel.event_listener, event: folder.on.crypt, method: onCryptFolder}
            - { name: kernel.event_listener, event: folder.on.decrypt, method: onDeCryptFolder}
            - { name: kernel.event_listener, event: folder.on.move, method: onMoveFolder}
            - { name: kernel.event_listener, event: folder.on.copy, method: onCopyFolder}
            - { name: kernel.event_listener, event: folder.on.sendInvit, method: onSendInvitation}
    app.event.file:
        class: App\EventListener\FileListener
        arguments: ['@app.file_log_manager', '@doctrine.orm.entity_manager', '@security.token_storage', '@translator']
        tags:
            - { name: kernel.event_listener, event: file.on.delete, method: onDeleteFile}
            - { name: kernel.event_listener, event: file.on.change_owner, method: onChangeFileOwner}
            - { name: kernel.event_listener, event: file.on.rename, method: onRenameFile}
            - { name: kernel.event_listener, event: file.on.move, method: onMoveFile}
            - { name: kernel.event_listener, event: file.on.copy, method: onCopyFile}
            - { name: kernel.event_listener, event: file.on.create, method: onCreateFile}
            - { name: kernel.event_listener, event: file.on.sendInvit, method: onSendInvitation}
            - { name: kernel.event_listener, event: file.on.download, method: onDownload}

    app.event.comment:
        class: App\EventListener\CommentListener
        arguments: [
          '@doctrine.orm.entity_manager',
          '@app.mailer',
          '@app.mail_automatique_manager',
          '@app.user_manager',
          '@security.token_storage'
          ]
        tags:
            - { name: kernel.event_listener, event: comment.on.create, method: onCreateComment}
            - { name: kernel.event_listener, event: comment.on.modify, method: onModifyComment}
            - { name: kernel.event_listener, event: comment.on.delete, method: onDeleteComment}

    app.peramlink:
        class: App\Services\Permalink
        public: true

    app.url_mapping_manager:
        class: App\Manager\UrlMappingManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\UrlMapping']
        public: true
    app.utils:
        class: App\Services\Utils
        arguments: ['@service_container', '@doctrine.orm.entity_manager', '@app.mailer','@app.openstack.objectstore']
        public: true
    app.sms:
        class: App\Services\Sms
        arguments: ["@service_container","@doctrine.orm.entity_manager"]
        public: true

    app.openstack.auth:
        class:  App\Services\OpenStack\Auth
        arguments: ['%ovh_openstack%']
        public: true

    app.openstack.objectstore:
        class:  App\Services\OpenStack\ObjectStore
        arguments: ['%ovh_openstack%']
        public: true

    'App\Swagger\SwaggerDecorator':
        decorates: 'api_platform.swagger.normalizer.documentation'
        arguments: [ '@App\Swagger\SwaggerDecorator.inner' ]
        autoconfigure: false

    app.view_manager:
        class: App\Manager\ViewManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\View']
        public: true
        
    app.user_preference_manager:
        class: App\Manager\UserPreferenceManager
        arguments: ['@doctrine.orm.entity_manager', 'App\Entity\UserPreference']
        public: true